### ISSUE TITLE
Add support for translate button

### ISSUE THREAD

**Issue by NguyenASang** [r-plus/MenuSupport#3]
## Feature request
Add support for Tranzlo's translation button in system menu.

**Comment by NguyenASang** [comment]
@r-plus Are you working on this ?

**Comment by r-plus** [comment]
What do you mean ‘Tranzlo‘?

**Comment by NguyenASang** [comment]
I mean Tranzlo tweak from Miro repo: https://miro92.com/repo/

Replace "To Vietnamese" with a translation button

![IMG_7605](https://github.com/r-plus/MenuSupport/assets/87893636/fd13779c-eb33-4798-87a1-9994d51301af)

**Comment by r-plus** [comment]
That is not addon of MenuSupport.
I’ll not support 3rd party tweak added menu.

I think sending feature request to Tranzlo's author is appropriate way to iconize.

**Comment by NguyenASang** [comment]
Sadly he dropped iOS 12 support, thank you anyway
